### ISSUE TITLE
Chat Spam Blocker doesn't work with Platinum Client?

### ISSUE THREAD

**Issue by Spezialeinheit** [gravitylow/AntiCheat#104]
Today I had a small children's spam attack on my server. Logs:

http://pastebin.com/iuctEz5Q

The Player uses: http://www.youtube.com/watch?v=0ILbLkv3-4w&feature=youtu.be&t=4m43s

They might get kicked out, but can still always go back to the server and get out. If they are kicked out, is not in the log anticheat are kicked player ....

I have "log to console" to true.

**Comment by SuperSpyTX** [comment]
Two things are wrong here, but i can't blame you.

First off, this tracker is officially no longer in use, but since @h31ix is derpus at his new bug tracker, doesn't matter here.

Secondly, AntiCheat's antispam protection isn't as good as some other plugins.  Because you had an attack, I would recommend AntiBot for your server (http://dev.bukkit.org/server-mods/antibot).  If you decide to go with AntiBot, you won't have to disable AntiCheat's antispam as it is disabled for you automatically.
