### ISSUE TITLE
Cheats That still work

### ISSUE THREAD

**Issue by LordDWT** [gravitylow/AntiCheat#129]
These still work when using Nodus.

Fast Place
Aim Bot
Force field
Timers
Auto-Egg
Wall Hack
ESP
Auto Sign
Smasher (Nuke Smasher)

Probably more that I haven't tested yet.

**Comment by gravitylow** [comment]
Can't fix anything client-side such as ESP/Wall Hack, but I've pretty much tested the rest and seen them blocked pretty recently actually.. We set up a testing initiative and most of these are verified as fixed. 

If you're really experiencing issues I'll look into it, but it's very surprising. What's your AntiCheat version, and may I have a **/anticheat debug** log please?

**Comment by LordDWT** [comment]
Version: [INFO] AntiCheat version 1.5.3

Debug log : http://pastebin.com/mzs8QsqT
YouTube Videos: http://youtu.be/Z9mu_NrCS8Y
http://youtu.be/bgVknfyADbk

Diamond Pickaxe Efficency IV picking up as Fast Break
Debug log: http://pastebin.com/aMGH0egE
YouTube Videos: http://youtu.be/XvufpZ7obQM

Thanks for your attention.

On Sun, Dec 30, 2012 at 5:08 PM, H31IX notifications@github.com wrote:

> Can't fix anything client-side such as ESP/Wall Hack, but I've pretty much
> tested the rest and seen them blocked pretty recently actually.. We set up
> a testing initiative and most of these are verified as fixed.
> 
> If you're really experiencing issues I'll look into it, but it's very
> surprising. What's your AntiCheat version, and may I have a _/anticheat
> debug_ log please?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/h31ix/AntiCheat/issues/129#issuecomment-11769948.

## 

-= David Tadlock =-
 Of all the things I've lost,
I miss my mind the most. ~ Mark Twain

**Comment by SuperSpyTX** [comment]
Alright based on the review of this video, 1 bug was fixed (Fastplace).

I will only review the items that were shown in the video.
- Aimbot & Forcefield are currently difficult to block right now, even on NoCheatPlus.
- Fastplace was because of code logic that appears to have been bypassed by Nodus.
- The Fastbreak check is pretty new, as it now calculates block damage.  The only issue right now is Bukkit API is currently lacking access to a method (which at this point, would've used NMS) that determines the correct efficiency for the block breaks, due to this, there will be obvious false positives with pickaxes with enchantments etc.  Until they either expose this part or I get around to it, there will be the obvious false positive.  This is one of the reasons why h31ix reverted to the old fastbreak code in the commits (and now switched back due to severity of false positives).

You can test Fastplace as you like, but I've tested it before I committed the code.

As for the other items on that list, they were not shown in the video or little information was provided for them so they were not reviewed.

I will go ahead and close this now, if you have extra information you would like to provide, you can do so and I'll reopen the ticket.

EDIT: Oops, fastplace, not fastbreak.

**Comment by LordDWT** [comment]
I showed timers in the video.  It still allows the player to move very quickly.
 Anticheat does log the event but does nothing to stop it.

Auto-Egg allows you say spawn 64 eggs at once which if in survival should not be an issue.
Auto Sign allows "fast place" of signs
As for the others there either client side or probably don't have much impact.
And Smasher quickly breaks down torchs/crops.  I'll get some vids of this tomorrow.

**Comment by SuperSpyTX** [comment]
I tested Timers and it looks like it still needs tweaking.

As far as AutoSign goes, I believe that is not blocked.

**Comment by LordDWT** [comment]
Here's some new Vids

Auto-Egg won't be effective unless you had an egg stack
Auto-Egg: http://youtu.be/3D7cGWivSc8

Auto-Sign: http://youtu.be/SqRWXyVf0Yw

Nuke Smasher :http://youtu.be/5qK1QKZveCg
This Disconnect you see at the end was lagg or an overflow of the client that caused and "End of Stream" notice

I really appreciate you looking at these and responding back.  Very impressive.  
Most Devs (that I've encountered) are rude but you sir are awesome!
