### ISSUE TITLE
xAuth

### ISSUE THREAD

**Issue by LordDWT** [gravitylow/AntiCheat#130]
Can you look into making this compatible with xAuth?

What happens is once your session expires and you login it attempts to move to to a default spawn point to allow you to login.  Anti-Cheat senses this as "Speed Hack" and stops the movement.  This will cause your player to become stuck inside a block and nothing can be done except suffocate to death or take massive fall damage..ect.

Debug log http://pastebin.com/Zb7rKzfe

[INFO] AntiCheat version 1.5.3

CraftBukkit version git-Bukkit-1.4.6-R0.3CraftBukkit version git-Bukkit-1.4.6-R0.3

**Comment by SuperSpyTX** [comment]
I can actually see why this is the case, as I don't remember actually putting a check if the user just teleported.

Normally, I would've gone over the ticket and see that this is a plugin issue.  Because this issue has to do with teleporting (EDIT: And the fact the "tried to fly" check is recently new), this makes the ticket relevant.

I'll investigate and maybe just push a commit to fix this issue.

**Comment by SuperSpyTX** [comment]
If the problem persists, contact the authors of xAuth and nag them to use our API.

**Comment by LordDWT** [comment]
Thanks for the help I'll check it out once the new download is available.

**Comment by gravitylow** [comment]
See http://ci.h31ix.net/job/AntiCheat/
