### ISSUE TITLE
Stargate bug (y-axis-check)

### ISSUE THREAD

**Issue by Trikolon** [gravitylow/AntiCheat#146]
False positives when players use portals from Stargate

It occurs when a player enters a portal, it teleports him to his destination, then freezes him in place and throws out hacking-warnings. (fly on y-axis)

Furthermore I experienced that it teleports players very high up in the air and lets them fall down after using a portal, but that occured rarely.

Here you have the debug:
http://pastebin.com/F3bxy198

**Comment by gravitylow** [comment]
Wasn't able to duplicate.

**Comment by Trikolon** [comment]
Only some portals have these issue, it does not always happen.

**Comment by gravitylow** [comment]
Hmm... do you have any specifics on those portals? E.g. distance? Are they cross-worlds? Are they in a cave or on the ground? etc.

**Comment by Trikolon** [comment]
No issues with cross-world-portals at all. It might be the distance, the destionations of these portals are quite near. Or could it be the portal-layout?

**Comment by ha11oga11o** [comment]
Im using [TP] Stargate v0.7.9.2 - The Bukkit port. A portal plugin. And portals are near each other about 40-50 blocks, but vertically.

**Comment by Gotxi** [comment]
It happens to me too. When you use a stargate portal to travel from an Y axis to an increased value of Y, most of the times (not always) gives a fly hack warning. Does not happen when you travel through a portal from an Y superior to a lesser Y value.

This is an example of the server log kicking me:
http://pastebin.com/Lr60sawH

**Comment by SuperSpyTX** [comment]
Based on the comments of this issue, it sounds like Stargate does some pretty nasty stuff in the PlayerMoveEvent.

**Comment by SuperSpyTX** [comment]
Yeah, it appears the author of Stargate decided to manipulate the event by setting the setTo() instead of using .teleport().
https://github.com/TheDgtl/Stargate-Bukkit/blob/master/src/net/TheDgtl/Stargate/Portal.java#L483

Anyways, complain to TheDgtl if you want this fixed.

**Comment by gravitylow** [comment]
Going to disagree on this one. The API has setTo for a reason, and it's not just stargate that makes use of it. I'll look into it soon.

**Comment by Gotxi** [comment]
This is a video of me with my OP account using a portal to an upper level:
http://www.youtube.com/watch?v=dAODzwZUTdk

And this is a video of me with my player account using the same portal:
http://www.youtube.com/watch?v=LR5SV2QAGKE

And this is the log of the player:
http://pastebin.com/JZ29SLYv

If this helps...

**Comment by Elharter** [comment]
The same error on my server.... i use stargate and installed anticheat since 10minutes... some "clean" players are kicked if they use Stargate-Portals in the same world.

Only one thing is conspicuously..... the kick/error appears if one of the portals is higher or lower then the other one.

Need help too, i open a own 2nd ticket

**Comment by Trikolon** [comment]
No 2nd one needed as its exactly the same issue.

**Comment by SuperSpyTX** [comment]
It'd still be nice for Stargate to change /some/ of it's ways.

**Comment by gravitylow** [comment]
I've contacted Drakia about that issue in the past he's not willing to make any sort of changes to it.

**Comment by SuperSpyTX** [comment]
Welp, another portal plugin down until this issue is either resolved or you stop using the plugin.

**Comment by Elharter** [comment]
is it not possible to programm an exception for stargate´s ?

A possible way:
When a player enters a stargate-portal (detected by easy command -> stargate.use) he is ignored for 3 second from Anticheat on X and Y axis.

That sould be realizable.

**Comment by gravitylow** [comment]
I don't add detection for plugins and exempt them from the system by name because then I would be forced to add exceptions for all these different plugins. That's not my job. Plugins that modify vanilla behaviour aren't my problem; they are the plugin author's. I built an API so THEY can fix the issue, but I'm not keeping track of everything in addition to what I already have to do. 

Furthermore, simply doing this is just a patch over the actual issue at hand, and doesn't really fix anything. With that said, as I said I WILL be looking into this to see if there's something we can add to the check to make sure modified to values are ignored. But I'm not detecting commands or watching for plugins or whatever.

**Comment by Elharter** [comment]
so conclusion is: that is a ping pong game between stargate-author and you ... no resolution in sight - or ?

What should we do with our 30-70 players online?
Delete Stargate? Not possible with over 70 Gates on our Server...

We installed Anticheat since 2 Days and there are many many false errors / kicks and bans.....thats a really bad advertising for anticheat plugin.

Our decision fell on anticheat because of a big compatibility, notably the compatiblity with mcmmo....

What should i do now in my case?

**Comment by gravitylow** [comment]
Exempt players temporarily from fly, and I'll be working on this tomorrow. I just finished finals week, so I have spare time to fix this on our end. 

As far as resolutions go (ACTUALLY solving the issue), I wish I could have a more understanding conversation with some plugin authors, but few are as receptive and willing to make change as some are. The entire reason AntiCheat is dependency-free and still compatible with stuff like mcMMO is because Nossr50/the mcMMO team are such badasses and are welcoming of discussion about the topic. Some are not, but it isn't something I can change. I'll do what I can.

The actual quote I have from Drakia from may 15th of last year (this isn't a new issue, it's just been patched and patched and patched) is `I do not code my plugins to work around other plugins, and as such will not be adding an API call specifically for your plugin.`

**Comment by Elharter** [comment]
on our server ONLY Admins have fly-permissions.... all long routes are bridged with stargate-portal...
So we have Stargate´s to our farm-worlds, Stargate´s to all adminshops, to other citys and so on....

In combination with this current error the full gameplay is currently broken and damaged, because there is no way to travel between all places with long distances.

For the first look, anticheat is great! So id like to use it more and longer.
In the meanwhile i must deactivate the plugin if there is no resolution in sight.

Thats really crap - because we have many many cheaters and hackers on our server.

My idea (detect stargate.use command, and ignore x/y axis for ~3sec) should only be a workaround, as long as a real-usable resolution in sight..... it was only an idea.
I tought it is a very little programming change, with maximum 10-15 lines of code.....

Inform if there are some news....big thanks for fast response.

**Comment by gravitylow** [comment]
Well I don't really know how removing AC makes this better than just turning off fly because of the security thing, but okay. In any case, I've pushed a fix that shoulddddd correct this issue, but I'm right in the middle of bugfixing so it hasn't been tested yet; just wanted to get one up there as quick as possible for you because I know this is a game-breaking bug.

**Comment by Gotxi** [comment]
Thats very considerate, im willing to test it :)

**Comment by gravitylow** [comment]
Is this fixed or?

**Comment by Trikolon** [comment]
No, not fixed. Or are we talking about dev-builds?

**Comment by gravitylow** [comment]
Commit https://github.com/h31ix/AntiCheat/commit/c1af360c9f2cddcdd34d2cce144db7bab5347cb0 was pushed 24 days ago and the changes are present in http://ci.h31ix.net/job/AntiCheat/418/

They implement a new listener to make sure other plugins have a chance to modify the values on their end first. Checking to see if this achieves the proper compatibility would be appreciated.

**Comment by Trikolon** [comment]
Thank you very much. This seems to be fixed. (Using v1.5.6-DEV-b431)
