### ISSUE TITLE
sprinted while standing still (xyz = -88,16,19)

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#151]
Player just jumped into MultiVersePortal while was sprinting and got violation level increased. 
http://pastebin.com/T27H6TcP
Also, I would like to set user to MEDIUM when he uses "spider" hack for the first time and HIGH for when he gets 5 violation level. How it's possibly done with AntiCheat? All other check punishments are fine with global violation. But "spiders"... They are special... 100% cheaters. I've got innocent players with speed, nofall and even fly hack violation. But NEVER with spider. 
//Love new debug :3

**Comment by columb** [comment]
https://dl.dropbox.com/u/27770548/dfq.PNG
How?

**Comment by gravitylow** [comment]
I'll look into the bug in question.

Regarding your question about spider, there's no API currently implemented that allows server administrators to do this easily without compiling AntiCheat themselves. If it's something you're interested in, please open a seperate ticket and mark it as a suggestion so I can keep track of it.

Regarding your picture, AntiCheat drops player's levels after action is taken on them to make sure they don't get above your high limit and therefor become invincible against any checks (because they never enter a level again, subsequently causing no actions). I assume this is what happened in your photo, but I don't know without proper information.

**Comment by gravitylow** [comment]
I wasn't able to duplicate the run/jump portal issue.

**Comment by columb** [comment]
Doesn't have new complaints about this issue from players, could be closed. Weird.
