### ISSUE TITLE
Default max speed value in magic.yml should be changed.

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#158]
XZ_SPEED_MAX: 0.25 -> 0.4 (Needs testing, but my players are able to speed up to 0.39 without hacks on parkour maps.
http://pastebin.com/MrcrEXPR

**Comment by ryantheleach** [comment]
its lag related, different countries have differing tolerances, + lan vs otherwise, so IMO the defaults should be rather strict, and allow admins to slack them off.

it would be great however, if there was someway to statistically analyse such things, but would be much beyond the scope of anticheat...

maybe there could be a recommended file included with magic, that contains values the community finds to work well.

**Comment by gravitylow** [comment]
Maybe I'll look into creating an easy system where people can vote on the best values, but as I've said before, they're only a patch to a problem - NOT a proper fix. If there's something wrong, it needs to be fixed internally which is why I won't be making this big of a leap.

**Comment by columb** [comment]
It's parkour server. Sure it's 20/20 TPS and there almost none connection problems. Also, add server TPS to debug info.

**Comment by gravitylow** [comment]
People need to stop measuring things in TPS. TPS means almost nothing, and shouldn't serve as an accurate measure of your server's performance. Furthermore, it has nothing to do with network performance, which is what @ryantheleach was talking about.

**Comment by columb** [comment]
Minecraft doesn't use too much bandwidth. Got ~30MB output bandwidth with total online of ~300 players. But CPU usage is probally means a lot, since minecraft  terrible handling multicore.

**Comment by gravitylow** [comment]
I don't think you're entirely knowledgeable enough on the subject to make an accurate representation of this. This isn't about bandwidth... Also, Minecraft doesn't have terrible multicore handling because it doesn't... handle multicore at all... Minecraft is single-core. CPU usage isn't really a problem if you're not running the server off a laptop. In any case, this is all irrelevant to the fact that you're suggesting using TPS as a measurement of server & network capability; IT IS NOT.

**Comment by columb** [comment]
@h31ix 

> CPU usage isn't really a problem 

http://www.minecraftwiki.net/wiki/Tick

Yes it is! I guess you doesn't have to deal with large amount of players.
I've got total (I have several servers) online about 300 players. And my hardware stats are 64 GB of ram and i7-3820 (Gonna upgrade it to 3930K). I guess, this doesn't sound like typical laptop-based server. Beside this I'm dealing with minecraft server since beta 1.3. (Yeah, that's about 2 years)  
 Some plugins DO able to work with multithread and even some parts of craftbukkit (not sure if only spigot or CB too) are able too (Chunk loading with multithread for example) but this isn't enough and only one core are get overloaded. The only thing I care about is TPS due to this the only one way to know when your server lag. I don't have problems with RAM at all and my average network usage are quite acceptable. As you may notice on bukkit/spigot/spout forums other server admins are care about TPS too. 
More players → more cpu load → lower ticks → OMGLAG.
I would like to summon @md-5 to prove it.
