### ISSUE TITLE
[SEVERE] Could not pass event InventoryOpenEvent to AntiCheat v1.5.4

### ISSUE THREAD

**Issue by ha11oga11o** [gravitylow/AntiCheat#161]
Hello,

i have these issues on server since i update to newest release version R: AntiCheat v1.5.4 for CB 1.4.7-R0.1 14 hours ago. Im using CB 146R03 beta. What this error is and how to fix it, avoid, or whatever i can do at mine side?

Many thnx:)

http://pastebin.com/tBYaKC2F

**Comment by det0nat3** [comment]
Running into this same issue on our server.

AntiCheat v1.5.4
Bukkit-1.4.6-R0.3-b2586jnks

**Comment by kingpyro** [comment]
same error

Anticheat v1.5.4
CB: 1.4.7 B2608

**Comment by gravitylow** [comment]
Could each of you guys provide debug logs (/anticheat debug) and a pastebin of the error so I can compare, please? Thank you, I'll work on fixing it as fast as I can with this information.

**Comment by det0nat3** [comment]
not sure what triggers the error.

Debug: http://pastebin.com/Hy7CG771
Error: http://pastebin.com/NTxXXsGq

**Comment by gravitylow** [comment]
I've discovered that the bug seems to come from people opening beacons. Working on a fix now.

**Comment by gravitylow** [comment]
Fixed and pushed as 1.5.5, reload/restart your server (if auto-update is on) and you should get the new build soon. Otherwise, you can download from this page: http://dev.bukkit.org/server-mods/anticheat/files/26-anti-cheat-v1-5-5/

In my opinion this is a bug that needs to be fixed by Bukkit, and I'll be working on a commit to do so as this is an internal bug (any beacon opened will return inventory contents that don't exist)
