### ISSUE TITLE
Overly aggressive system.

### ISSUE THREAD

**Issue by ErinKitty** [gravitylow/AntiCheat#175]
Unfortunately had to remove this from my server.
It's far too aggressive with players, they're getting kicked constantly for fast place, fast break and no swing.
We've read the other tickets where other people have the same problem and you suggested changing things in the .yml file, it made no difference.
We've lost a lot of players due to the constant kicking or warnings.
But we now worry the server is not safe as we have no way of checking up on hackers and using the anticheat report.
Is there any way this could be fixed?

May I suggest that warnings and reports only get showns to admins and not to the accused player, that way we can monitor them without causing suspicion.
Thanks for your time.

**Comment by gravitylow** [comment]
If you have a specific issue, I need to have the debug info (/anticheat debug) and a proper, specific report. While I do understand your concerns, a general report like this doesn't provide me with any way to properly fix the issue. I'm sure you can understand that saying "X is broken because Y" is a lot better than "XYZ don't work". I'm a one-man-team, and so I really can't spend too much time debugging this all myself.

As far as warnings go, you can turn on silent mode to avoid the players knowing about the system; it's specifically designed for that purpose and is toggleable in the config.

Closing this report for now.
