### ISSUE TITLE
BUG some times my players get hit

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#193]
Debug http://pastebin.com/JaSH2NWz

sometimes my players get hit i have tested it with all my other plugins disabled and it mostly 
hapens when i am in water can you fix this bug

**Comment by gravitylow** [comment]
When I said "make a coherent report" I didn't mean "copy and paste the content from your last post so that I still can't understand what you're trying to say".

I have NO idea what you're talking about. "Sometimes my players get hit"?!? What is that supposed to mean and why does it involve me? 

As far as adding the debug report, you still haven't followed my instructions. Here is what I said the last time I linked you to the readme

> Note that for the debug output to contain valid information and help us diagnose your issue, you need to issue this > command AFTER the issue occurs at least once and BEFORE you reload or restart it.

**Comment by typhoonwes** [comment]
Hi, i have the same problem, but worst.
When players open inventory and start moving stuff around, They die and lose anything they had on them. It does not even drop it.

Other times, jumping up onto 1 block, you get hurt.

No error in console. 
I had to disable the plugin for now.
i am using your lastest Jenkins build after this started to happen.

**Comment by gravitylow** [comment]
Your two issues are completely unrelated. File your own bug report so I can keep track of the issues.

**Comment by xsonarx** [comment]
@typhoonwes 

Known issue: https://github.com/h31ix/AntiCheat/issues/189

**Comment by gravitylow** [comment]
Closing because I still have no clue what the op is talking about. As I said on the last one, please describe your issue coherently; I don't read minds
