### ISSUE TITLE
no more xray logs in /anticheat xray after log out. MySQL?

### ISSUE THREAD

**Issue by KhaarNaj** [gravitylow/AntiCheat#227]
So,

I'm using Anticheat since a week, it's a very powerful tool that I can use to check players that could be using some cheats.

The biggest problem I have on my server is xray. It seems that anticheat no longer consider xray stats of older sessions from players, it starts from 0 at each log in. And if the player is not online I can't have any report for him.

What about considering the option of a MySQL database? Or can I set this otherwise?

Thanks a lot for reading and your answers. :)

KhaarNaj

**Comment by gravitylow** [comment]
This is an intentional design feature. The limited life of the XRay statistics is necessary to ensure the data collected is accurate. It is not every login, but rather every time the server is reloaded or restarted that the buffer is cleared.

I'll explain it this way. Say a player comes onto your server and starts playing. He's having a great time, playing by the rules, etc. Meets some friends and starts talking with them, and they decide to use xray clients. They've all been on the server for a period of weeks or months at this point. Now, if the plugin were to use SQL to log ALL the blocks they've broken from the entire time they've played on your server, what do you think the ratio of their newly found ores would be to "normal" blocks? It'd probably be entirely realistic; they've been playing legitimately and have many, many more legitimate mines that are only now being xrayed.

In that situation, it could take a period of even longer to determine that they're xraying; weeks or months. The way it is NOW, the players would be caught within a matter of hours, because they are mining an entirely unrealistic amount of ores in such a short time.

Counting the past statistics of players is an needed and statistic, and its presence is detrimental to the calculations.

**Comment by KhaarNaj** [comment]
Ok, but what about a possibility that moderators and admins could check last session or more (like 10 last hours or last week?)

**Comment by DrSalty** [comment]
Would be nice to have a set of stats for each server reset then. Going back say 7 to 14 server resets (or days) however you want to break it up for the best statistical analysis.
