### ISSUE TITLE
Angry Letter

### ISSUE THREAD

**Issue by nejcneo** [gravitylow/AntiCheat#87]
Really ? "DEV BUILD #205 "
205 Builds and still not working!!

Errors:
-If you type anything you will get "Don't spam" (WTF ? I tryed by myself I typed: test, I get "don't spam)
## \- IF you go on stairs you will be kicked because hacking !?!?!?

I think "NoCheat+" is much better then this crap. And no I am not hater, but this is real crap, try by yourself, Put it on your server for 1 min and you will get 100+ Hacking kicks just like that.

Changing to NoCheat+...

**Comment by gravitylow** [comment]
Literally not a single other person using AntiCheat has experienced this issue, and we've been testing #205 for over 5 days. Even if you were not so rude I would not look into this issue, because it clearly does not exist. We test builds daily, and no real issues about spamming, and definitely no issues with stairs are present.

I do "try by myself" so thanks, and have a nice day.
